<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <link name="base_link"/>
    
    <!-- CHASSIS -->
    <xacro:property name="chassis_origin_xyz" value="0.05 0 0.125"/>
    <xacro:property name="chassis_origin_rpy" value="0 0 0"/>
    <xacro:property name="chassis_size_x" value="0.3"/>
    <xacro:property name="chassis_size_y" value="0.3"/>
    <xacro:property name="chassis_size_z" value="0.15"/>
    <link name="chassis">
        <visual>
            <origin xyz="${chassis_origin_xyz}" rpy="${chassis_origin_rpy}"/>
            <geometry>
                <box size="${chassis_size_x} ${chassis_size_y} ${chassis_size_z}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${chassis_origin_xyz}" rpy="${chassis_origin_rpy}"/>
            <geometry>
                <box size="${chassis_size_x} ${chassis_size_y} ${chassis_size_z}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="${chassis_size_x}" y="${chassis_size_y}" z="${chassis_size_z}">
            <origin xyz="${chassis_origin_xyz}" rpy="${chassis_origin_rpy}"/>
        </xacro:inertial_box>
    </link>
    
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 -0.05"/>
    </joint>
    
    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>
    
    <xacro:property name="wheel_length" value="0.04"/>
    <xacro:property name="wheel_radius" value="0.05"/>
    <!-- LEFT WHEEL -->
    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <xacro:property name="wheel_distance" value="0.35"/>
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_distance/2} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>
    
    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
    
    <!-- RIGHT WHEEL -->
    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 -0.175 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>
    
    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
    
    <!-- CASTER WHEEL -->
    <xacro:property name="caster_radius" value="0.05"/>
    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.1" radius="${caster_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>
    
    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="0.09 0 0.05" rpy="0 0 0"/>
    </joint>
    
    <gazebo reference="caster_wheel">
        <material>Gazebo/Black</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>
    
    <plugin name="gazebo_ros_joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
        <update_rate>20</update_rate>
        <joint_name>chassis_joint</joint_name>
        <joint_name>left_wheel_joint</joint_name>
        <joint_name>right_wheel_joint</joint_name>
        <joint_name>caster_wheel_joint</joint_name>
    </plugin>

</robot>
